export async function getJobs() {
  return [
    {
      id: 1,
      title: "Software Engineer",
      company: "Google",
      location: "Mountain View, CA",
      postedAt: new Date("2024-01-15"),
      workplaceType: "Hybrid",
      technologies: ["React", "TypeScript", "Node.js", "GCP"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 2,
      title: "Frontend Developer",
      company: "Facebook",
      location: "Menlo Park, CA",
      postedAt: new Date("2024-01-14"),
      workplaceType: "Remote",
      technologies: ["React", "JavaScript", "GraphQL", "Redux"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 3,
      title: "Full Stack Developer",
      company: "Netflix",
      location: "Los Gatos, CA",
      postedAt: new Date("2024-01-13"),
      workplaceType: "On-site",
      technologies: ["Vue.js", "Python", "AWS", "Docker"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 4,
      title: "Backend Engineer",
      company: "Amazon",
      location: "Seattle, WA",
      postedAt: new Date("2024-01-12"),
      workplaceType: "Hybrid",
      technologies: ["Java", "Spring", "AWS", "Kubernetes"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 5,
      title: "DevOps Engineer",
      company: "Microsoft",
      location: "Redmond, WA",
      postedAt: new Date("2024-01-11"),
      workplaceType: "Remote",
      technologies: ["Azure", "Terraform", "Jenkins", "Docker"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 6,
      title: "Data Scientist",
      company: "Apple",
      location: "Cupertino, CA",
      postedAt: new Date("2024-01-10"),
      workplaceType: "On-site",
      technologies: ["Python", "TensorFlow", "SQL", "Jupyter"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 7,
      title: "Machine Learning Engineer",
      company: "Tesla",
      location: "Palo Alto, CA",
      postedAt: new Date("2024-01-09"),
      workplaceType: "Hybrid",
      technologies: ["Python", "PyTorch", "MLflow", "Kubernetes"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 8,
      title: "Cloud Architect",
      company: "Salesforce",
      location: "San Francisco, CA",
      postedAt: new Date("2024-01-08"),
      workplaceType: "Remote",
      technologies: ["AWS", "Salesforce", "Apex", "Lightning"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 11,
      title: "Cloud Architect",
      company: "Salesforce",
      location: "San Francisco, CA",
      postedAt: new Date("2024-01-08"),
      workplaceType: "Remote",
      technologies: ["AWS", "Salesforce", "Apex", "Lightning"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 9,
      title: "Cloud Architect",
      company: "Salesforce",
      location: "San Francisco, CA",
      postedAt: new Date("2024-01-08"),
      workplaceType: "Remote",
      technologies: ["AWS", "Salesforce", "Apex", "Lightning"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 10,
      title: "Cloud Architect",
      company: "Salesforce",
      location: "San Francisco, CA",
      postedAt: new Date("2024-01-08"),
      workplaceType: "Remote",
      technologies: ["AWS", "Salesforce", "Apex", "Lightning"],
      source: "https://www.linkedin.com/",
    },
    {
      id: 12,
      title: "Cloud Architect",
      company: "Salesforce",
      location: "San Francisco, CA",
      postedAt: new Date("2024-01-08"),
      workplaceType: "Remote",
      technologies: ["AWS", "Salesforce", "Apex", "Lightning"],
      source: "https://www.linkedin.com/",
    },
  ];
}
